package com.invoice.processing;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.fasterxml.jackson.databind.ObjectMapper;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.services.dynamodb.model.GetItemRequest;
import software.amazon.awssdk.services.dynamodb.model.GetItemResponse;
import software.amazon.awssdk.services.dynamodb.model.UpdateItemRequest;

import java.time.Instant;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

/**
 * TokenApprovalHandler – handles one-click Approve / Reject links embedded
 * in SES notification emails.
 *
 * API Gateway route:
 *   GET /invoices/approve?token=<base64token>
 *   GET /invoices/reject?token=<base64token>
 *
 * Token format (Base64-encoded JSON):
 *   { "invoiceId": "# 11502", "decision": "APPROVED", "exp": 1718000000 }
 *
 * The token is generated by InvoiceExtractionHandler when it sends the
 * REVIEW_REQUIRED notification email. Tokens expire after 72 hours.
 *
 * On success, returns an HTML page confirming the decision.
 */
public class TokenApprovalHandler
        implements RequestHandler<Map<String, Object>, Map<String, Object>> {

    private static final String DYNAMO_TABLE         = "invoices";
    private static final long   TOKEN_TTL_SECONDS    = 72 * 60 * 60L; // 72 hours

    private final DynamoDbClient dynamoDbClient = DynamoDbClient.builder()
            .region(Region.AP_SOUTH_1).build();

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Override
    public Map<String, Object> handleRequest(Map<String, Object> event, Context context) {
        try {
            context.getLogger().log("TokenApproval EVENT: "
                    + objectMapper.writeValueAsString(event));

            // ── Get token from query string ────────────────────────────────────
            String token = null;
            Object qsp = event.get("queryStringParameters");
            if (qsp instanceof Map) {
                token = (String) ((Map<?, ?>) qsp).get("token");
            }

            if (token == null || token.isBlank()) {
                return htmlResponse(400, "Invalid Request",
                        "❌ Missing approval token.", "#fee2e2", "#b91c1c");
            }

            // ── Decode and validate token ──────────────────────────────────────
            TokenPayload payload;
            try {
                String json = new String(Base64.getUrlDecoder().decode(token));
                payload = objectMapper.readValue(json, TokenPayload.class);
            } catch (Exception e) {
                return htmlResponse(400, "Invalid Token",
                        "❌ The approval link is invalid or corrupted.", "#fee2e2", "#b91c1c");
            }

            // Check expiry
            if (payload.exp < Instant.now().getEpochSecond()) {
                return htmlResponse(400, "Link Expired",
                        "⏰ This approval link has expired (72-hour limit).\n\nPlease log in to "
                        + "<a href=\"https://www.zexxity.online/review.html?id="
                        + encode(payload.invoiceId) + "\">the reviewer dashboard</a> to take action.",
                        "#fef3c7", "#b45309");
            }

            // Validate decision
            if (!"APPROVED".equals(payload.decision) && !"REJECTED".equals(payload.decision)) {
                return htmlResponse(400, "Invalid Decision",
                        "❌ Unknown decision in token.", "#fee2e2", "#b91c1c");
            }

            // ── Check if already decided ───────────────────────────────────────
            Map<String, AttributeValue> key = new HashMap<>();
            key.put("invoiceId", AttributeValue.builder().s(payload.invoiceId).build());

            GetItemResponse existing = dynamoDbClient.getItem(
                    GetItemRequest.builder().tableName(DYNAMO_TABLE).key(key).build());

            if (existing.hasItem()) {
                AttributeValue rd = existing.item().get("reviewDecision");
                if (rd != null && rd.s() != null && !rd.s().isBlank()) {
                    return htmlResponse(200,
                            "Already Decided",
                            "ℹ️ Invoice <strong>" + payload.invoiceId + "</strong> was already "
                            + rd.s() + ".<br><br>"
                            + "<a href=\"https://www.zexxity.online/review.html?id="
                            + encode(payload.invoiceId) + "\">View in dashboard →</a>",
                            "#fef3c7", "#b45309");
                }
            }

            // ── Write decision to DynamoDB ─────────────────────────────────────
            Map<String, AttributeValue> vals = new HashMap<>();
            vals.put(":decision",    AttributeValue.builder().s(payload.decision).build());
            vals.put(":reviewedAt",  AttributeValue.builder().s(Instant.now().toString()).build());
            vals.put(":reviewedBy",  AttributeValue.builder().s("email-link").build());
            vals.put(":note",        AttributeValue.builder().s("Approved via email link").build());

            dynamoDbClient.updateItem(UpdateItemRequest.builder()
                    .tableName(DYNAMO_TABLE)
                    .key(key)
                    .updateExpression(
                            "SET reviewDecision = :decision, "
                          + "    reviewedAt     = :reviewedAt, "
                          + "    reviewedBy     = :reviewedBy, "
                          + "    reviewNote     = :note")
                    .expressionAttributeValues(vals)
                    .build());

            context.getLogger().log("Email-link decision recorded: "
                    + payload.invoiceId + " → " + payload.decision);

            // ── Return confirmation HTML page ──────────────────────────────────
            boolean approved = "APPROVED".equals(payload.decision);
            return htmlResponse(200,
                    approved ? "Invoice Approved ✅" : "Invoice Rejected ❌",
                    (approved ? "✅" : "❌")
                    + " Invoice <strong>" + payload.invoiceId + "</strong> has been "
                    + "<strong>" + payload.decision + "</strong>.<br><br>"
                    + "This has been recorded in the system.<br><br>"
                    + "<a href=\"https://www.zexxity.online/index.html\" "
                    + "style=\"color:#6366f1;font-weight:700\">← Back to Dashboard</a>",
                    approved ? "#f0fdf4" : "#fff1f2",
                    approved ? "#15803d" : "#be123c");

        } catch (Exception e) {
            context.getLogger().log("TokenApproval ERROR: " + e.getMessage());
            return htmlResponse(500, "Error",
                    "❌ An unexpected error occurred: " + e.getMessage(),
                    "#fee2e2", "#b91c1c");
        }
    }

    // ── Helpers ────────────────────────────────────────────────────────────────

    private String encode(String value) {
        return value.replace("#", "%23").replace(" ", "%20");
    }

    private Map<String, Object> htmlResponse(int status, String title,
                                              String message, String bg, String color) {
        String html = """
                <!DOCTYPE html>
                <html lang="en">
                <head>
                  <meta charset="UTF-8"/>
                  <meta name="viewport" content="width=device-width,initial-scale=1"/>
                  <title>%s – Invoice Processing System</title>
                  <style>
                    * { box-sizing: border-box; margin: 0; padding: 0; }
                    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                           background: #0f172a; display: flex; align-items: center;
                           justify-content: center; min-height: 100vh; }
                    .card { background: #fff; border-radius: 16px; padding: 2.5rem 2rem;
                            max-width: 440px; width: 100%%;
                            box-shadow: 0 20px 60px rgba(0,0,0,.4); text-align: center; }
                    .icon  { font-size: 2.5rem; margin-bottom: 1rem; }
                    h1     { font-size: 1.2rem; color: #0f172a; margin-bottom: 1rem; }
                    .msg   { background: %s; color: %s; border-radius: 10px;
                             padding: 1rem 1.2rem; font-size: .9rem; line-height: 1.6; }
                    .brand { margin-top: 1.5rem; font-size: .75rem; color: #94a3b8; }
                  </style>
                </head>
                <body>
                  <div class="card">
                    <div class="icon">📄</div>
                    <h1>%s</h1>
                    <div class="msg">%s</div>
                    <div class="brand">zexxity.online · Invoice Processing System</div>
                  </div>
                </body>
                </html>
                """.formatted(title, bg, color, title, message);

        Map<String, Object> response = new HashMap<>();
        response.put("statusCode", status);
        response.put("headers", Map.of(
                "Content-Type",                "text/html; charset=UTF-8",
                "Access-Control-Allow-Origin", "*"
        ));
        response.put("body", html);
        return response;
    }

    // ── Token payload POJO ─────────────────────────────────────────────────────
    public static class TokenPayload {
        public String invoiceId;
        public String decision;
        public long   exp;
    }
}
